export { default as BuyConfirmed } from './BuyConfirmed/BuyConfirmed';
export { default as Cart } from './Cart/Cart';
export { default as Contact } from './ContactUs/Contact';
export { default as InputField } from './ContactUs/InputField';
export { default as CreateForm } from './CreateForm/CreateForm';
export * from './CreateForm/create-form-types';
export { default as FavoriteProducts } from './FavoriteProducts/FavoriteProducts';
export { default as ForgotPassword } from './ForgotPassword/ForgotPassword';
export { default as Home } from './Home/Home';
export { default as LandingPage } from './LandingPage/LandingPage';
export { default as SignInSide } from './Login/SignInSide';
export { default as Register } from './Register/Register';
export { default as ResetPassword } from './ResetPassword/ResetPassword';
